#ifndef IR_TX_H
#define IR_TX_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include "stm32f10x.h"

/*
 * IR Transmitter driver – NEC protocol, 38 kHz carrier
 *
 * Hardware: IR LED on any timer output pin (open-collector or push-pull
 *           with series resistor ~33 Ω).  Default: PA6 → TIM3 CH1.
 *
 * NEC frame (32 bits, LSB first):
 *   [address 8b][~address 8b][command 8b][~command 8b]
 *
 * Carrier generated by hardware PWM (1/3 duty cycle).
 * Bit timing via DWT cycle counter (µs precision).
 */

/* ------------------------------------------------------------------ types -- */

typedef struct
{
    GPIO_TypeDef      *port;             /* GPIO port of IR LED pin          */
    uint8_t            pin;              /* GPIO pin number 0-15             */
    GPIO_TypeDef      *etrPort;          /* GPIO port of TIMx_ETR pin        */
    uint8_t            etrPin;           /* GPIO pin number 0-15             */
    TIM_TypeDef       *timer;            /* Timer instance, e.g. TIM3        */
    uint8_t            channel;          /* Timer channel 1-4                */
    volatile uint32_t *timer_rcc_reg;    /* &RCC->APB1ENR or &RCC->APB2ENR  */
    uint32_t           timer_rcc_bit;    /* e.g. RCC_APB1ENR_TIM3EN         */
    uint32_t           afio_remap_mask;  /* AFIO_MAPR mask  (0 = no remap)  */
    uint32_t           afio_remap_val;   /* AFIO_MAPR value (0 = no remap)  */
    uint32_t           cpu_freq_hz;      /* CPU = timer clock frequency, Hz  */
} IR_TX_config_t;

/* ------------------------------------------------ well-known NEC addresses -- */

/* Cheap 44-key RGB LED strip controllers (very common) */
#define IR_ADDR_LED_STRIP    0x00u

/* LG TV (bonus) */
#define IR_ADDR_LG_TV        0x04u

/* Samsung TV (bonus – extended NEC / Samsung protocol, same frame format) */
#define IR_ADDR_SAMSUNG_TV   0x07u

/* ------------------------------------------------ well-known NEC commands -- */

/* --- 44-key RGB LED strip controller (address 0x00) --- */
#define IR_CMD_LED_POWER        0x40u
#define IR_CMD_LED_BRIGHT_UP    0x5Cu
#define IR_CMD_LED_BRIGHT_DOWN  0x5Du
#define IR_CMD_LED_RED          0x58u
#define IR_CMD_LED_GREEN        0x18u
#define IR_CMD_LED_BLUE         0x08u
#define IR_CMD_LED_WHITE        0x48u
#define IR_CMD_LED_FLASH        0x41u
#define IR_CMD_LED_STROBE       0x42u
#define IR_CMD_LED_FADE         0x43u
#define IR_CMD_LED_SMOOTH       0x44u

/* --- LG TV (address 0x04) --- */
#define IR_CMD_LG_POWER         0x08u
#define IR_CMD_LG_VOL_UP        0x02u
#define IR_CMD_LG_VOL_DOWN      0x03u
#define IR_CMD_LG_MUTE          0x09u
#define IR_CMD_LG_CH_UP         0x00u
#define IR_CMD_LG_CH_DOWN       0x01u

/* --- Samsung TV (address 0x07) --- */
#define IR_CMD_SAMSUNG_POWER    0x02u
#define IR_CMD_SAMSUNG_VOL_UP   0x07u
#define IR_CMD_SAMSUNG_VOL_DOWN 0x0Bu
#define IR_CMD_SAMSUNG_MUTE     0x0Fu
#define IR_CMD_SAMSUNG_CH_UP    0x12u
#define IR_CMD_SAMSUNG_CH_DOWN  0x10u

/* --------------------------------------------------------- public API ------ */

/**
 * @brief  Initialise the IR transmitter.
 *         Enables GPIO clock, configures pin as AF push-pull, starts timer
 *         PWM at 38 kHz and enables the DWT cycle counter.
 * @param  config  Pointer to filled IR_TX_config_t.
 */
void IR_TX_init(const IR_TX_config_t *config);

/**
 * @brief  Transmit a 32-bit NEC frame.
 *         Frame = address + ~address + command + ~command, LSB first.
 *         Duration ≈ 67.5 ms.  Blocking.
 * @param  address  8-bit device address.
 * @param  command  8-bit command code.
 */
void IR_TX_sendNEC(uint8_t address, uint8_t command);

/**
 * @brief  Transmit a NEC repeat frame (key held down).
 *         Should be sent every ~110 ms while key is held.
 *         Duration ≈ 11.25 ms.  Blocking.
 */
void IR_TX_sendNECRepeat(void);

void IR_TX_PWMOn(void);
void IR_TX_PWMOff(void);
#ifdef __cplusplus
}
#endif

#endif /* IR_TX_H */
